todo_app/config/routes.rb
Rails.application.routes.draw do
  resources :todos

  root 'todos#index'

end

todo_app/app/models/todo.rb
class Todo < ActiveRecord::Base
end

todo_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :notes)
    end
end

todo_app/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_app/app/helpers/todos_helper.rb
module TodosHelper
end

todo_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'navigation' %>
    <div class="container">

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </div>
  </body>
</html>

todo_app/app/views/todos/_form.html.erb
<div class="form-partial">

  <%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :title, class: "right inline" %>
        </div>
        <div class="small-10 columns">
          <%= f.text_field :title %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-2 columns">
          <%= f.label :notes, class: "right inline" %>
        </div>

        <div class="small-10 columns">
          <%= f.text_area :notes %>
        </div>
      </div>
    </div>

    <div class="small-10">
      <div class="row">
        <div class="small-10 small-offset-2 columns">
          <%= f.submit "Save",  class: 'button success radius tiny' %>
          <%= link_to 'Back', todos_path, class: 'button radius tiny' %>
        </div>
      </div>
    </div>
  </div>

<% end %>

</div>

todo_app/app/views/todos/_navigation.html.erb
<!-- Top Nav Bar with clickable link to home -->

<div class="sticky">

<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Foundation Todo</a></h1>
    </li>

    <li class="toggle-topbar">
      <a href="#"><span>Menu</span></a>
    </li>
  </ul>

<!-- Right Nav Section (Search) -->

<section class="top-bar-section">

            <ul class="right">
                <li class="has-form">
                    <div class="row collapse">
                        <div class="large-8 columns">
                            <input type="text" placeholder="Search for Todo">
                        </div>
                        <div class="large-4 columns">
                            <a href="#" class="button expanded">Search</a>
                        </div>
                </li>
            </ul>
        </section>

</nav>
</div>

todo_app/app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

todo_app/app/views/todos/index.html.erb
<h1>Foundation Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.notes %></td>
        <td><%= link_to 'Show', todo, class: 'button tiny radius' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: 'button tiny radius' %></td>
        <td><%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure? This action cannot be undone!' }, class: 'button tiny radius' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Todo', new_todo_path, class: 'button success radius tiny' %>

todo_app/app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

todo_app/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="show-form">
  <table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <td><%= @todo.title %></td>
    <td><%= @todo.notes %></td>
  </tbody>
</table>
<br>
    <td><%= link_to 'Back', todos_path, class: 'button radius tiny' %></td>
    <td><%= link_to 'Edit', edit_todo_path(@todo), class: 'button success radius tiny' %></td>
<div>